image: alpine:edge

stages:
  - deploy

before_script:
  - echo 'http://dl-cdn.alpinelinux.org/alpine/edge/testing' >> /etc/apk/repositories
  - apk -U add aws-cli

gitlab_pages:
  stage: deploy
  script:
    - echo 'Say your prayers, take your vitamins and you will never go wrong.'
  artifacts:
    paths:
      - public

s3:
  stage: deploy
  script:
    - echo 'Say your prayers, take your vitamins and you will never go wrong.'
    - aws s3 sync public/ s3://${S3_BUCKET} --acl public-read --delete
